Enterprise hosting support
shapehq/tartelet pull request #53
Opened 2023-10-04 06:23 UTC by mattia

Add the ability to specify an GitHub Enterprise Server URL so that users can use custom instances of self-hosted GitHub. The runner type `enterprise` is added so enterprises hosted on GitHub Cloud can add runners to the whole enterprise

2023-10-04 06:24 UTC, mattia commented
This PR is very much a WIP, there are a bunch of this to do before it is ready (code cleanup, duplication, etc.) but we need to verify that it is working before all and at the moment I don't have any ability to do it. Let's hope the community can share some feedback

2023-10-06 08:05 UTC, simonbs commented
@mattia Thanks a lot for opening this PR! I think it would be great to have this functionality in Tartelet. I'll make sure to review it once I have the time 😊

2023-10-06 10:17 UTC, mattia commented on Packages/VirtualMachine/Sources/VirtualMachineResourcesServiceEphemeral/VirtualMachineResourcesServiceEphemeral.swift
> +            return baseURL.appending(path: enterpriseName, directoryHint: .notDirectory)
This should be checked, from my understating of the API the base URL should be set on your instance URL, but in the example link they hardcode `github.com`. If anyone can confirm/update me on this, please let me know

2023-12-21 10:51 UTC, hoon-prestolabs commented
Any update?

2023-12-21 20:27 UTC, mattia commented
> Any update?

Hi @hoon-prestolabs! Unfortunately I don't have any news regarding this. The basic functionality is implemented and should work fine but I'm leaving the PR in draft because I don't want to propose this change without a feedback from users with this configuration.
If you are using GitHub Enterprise Server your feedback on this change would be welcome!

2023-12-21 20:31 UTC, mattia commented
(rebased the branch on `main` just to keep up with recent updates)

2024-01-03 21:37 UTC, simonbs requested changes
Once again, thank you for opening this PR and thank you for your patience. I apologize for the delay in responding.

I have added a few comments to the code changes. Some of the comments include required changes, such as ensuring texts are localized, and others include suggestions for improvements.

My main concern with merging these changes right now is that I am unable to test them myself, as I do not have access to an enterprise GitHub setup. I am also concerned about whether the new Version setting allows users to select an invalid combination of settings.

For example, is it valid to select the "github self hosted" and "organization" settings as shown in the screenshot below?

<img width="375" alt="1" src="https://github.com/shapehq/tartelet/assets/830995/7cbab91a-4b4c-44f3-a15f-62d68df275b3">

And is it valid to select the "github.com" and "enterprise" settings as shown below?

<img width="375" alt="2" src="https://github.com/shapehq/tartelet/assets/830995/8b7305d1-3299-4c50-a6ff-7eb86a06656e">

It is crucial that users cannot select an invalid combination of settings. However, since I have limited knowledge of GitHub's enterprise offerings, I am uncertain if this is achievable.

I am happy to continue with this PR if someone can verify that all combinations of settings are valid and that Tartelet exhibits the expected behavior.

2024-01-03 21:37 UTC, simonbs commented on Packages/Settings/Sources/SettingsUI/Internal/GitHubSettings/GitHubPrivateKeyPicker.swift
> +            "Check permissions: `manage_runners:enterprise`"
This text needs to be localized and formatted similar to the other texts listing required permissions.

2024-01-03 21:37 UTC, simonbs commented on Packages/Settings/Sources/SettingsUI/Internal/GitHubSettings/GitHubSettingsView.swift
> +                        "Self hosted URL",
This text needs to be localized and accessed through the L10n constant.

2024-01-03 21:37 UTC, simonbs commented on Packages/Settings/Sources/SettingsUI/Internal/GitHubSettings/GitHubSettingsView.swift
> +                        prompt: Text("Github Service raw value")
This text needs to be localized and accessed through the L10n constant.

2024-01-03 21:37 UTC, simonbs commented on Packages/Settings/Sources/SettingsUI/Internal/GitHubSettings/GitHubSettingsView.swift
> +                        "Enterprise name",
This text needs to be localized and accessed through the L10n constant.

2024-01-03 21:37 UTC, simonbs commented on Packages/Settings/Sources/SettingsUI/Internal/GitHubSettings/GitHubSettingsView.swift
> +            "Enterprise"
This text needs to be localized and accessed through the L10n constant.

2024-01-03 21:37 UTC, simonbs commented on Packages/Settings/Sources/SettingsUI/Internal/GitHubSettings/GitHubSettingsView.swift
> +                        prompt: Text("Acme Enterprise")
This text needs to be localized and accessed through the L10n constant.

2024-01-03 21:37 UTC, simonbs commented on Packages/GitHub/Sources/GitHubService/GitHubServiceVersion.swift
> +    case dotCom
I wonder if there's an official name for "standard GitHub" that we can use or if that's just "GitHub.com".

2024-01-03 21:37 UTC, simonbs commented on Packages/GitHub/Sources/GitHubService/GitHubServiceVersion.swift
> +  case enterprise(URL)
These enum cases don't seem to be used. Can we remove them and simplify this enum?

2024-01-03 21:37 UTC, simonbs commented on Packages/Settings/Sources/SettingsUI/Internal/GitHubSettings/GitHubSettingsView.swift
> +            return "github self hosted"
I'm unfamiliar with enterprise GitHub setups and self-hosting so please correct me if I'm wrong but the `enterprise` enum case seems to refer to GitHub Enterprise Server. Would it make sense to rename the case and the title to be more explicit about this and avoid confusion with the enterprise runner scope?

2024-01-03 21:37 UTC, simonbs commented on Packages/Settings/Sources/SettingsUI/Internal/GitHubSettings/GitHubSettingsViewModel.swift
> +                let repositoryName = tuple.3
This seems like a good opportunity to use tuple destructuring.

```suggestion
                let (runnerScope, organizationName, ownerName, repositoryName) = tuple
```

2024-01-03 21:37 UTC, simonbs commented on Packages/Settings/Sources/SettingsUI/Internal/GitHubSettings/GitHubSettingsView.swift
> +                Picker("Version", selection: $viewModel.version) {
This text needs to be localized and accessed through the L10n constant.

2024-01-03 21:37 UTC, simonbs commented on Packages/Settings/Sources/SettingsUI/Internal/GitHubSettings/GitHubSettingsView.swift
> +                }
Would it make sense to turn this picker into a segmented control to align with the Runner Scope setting?

```suggestion
                }
                .pickerStyle(.segmented)
```

2024-07-15 15:01 UTC, FloThinksPi commented
Hm i tried out the fork and at first it seemed to work well however when starting against a github enterprise server i got following error which i could not trace town yet:

```
Request to my-ghes-server.com/app/installations failed: unsupported URL
```

2024-07-15 15:33 UTC, mattia commented
> Hm i tried out the pr branch and at first it seemed to work well however when starting against a github enterprise server i got following error which i could not trace town yet:
> 
> ```
> Request to my-ghes-server.com/app/installations failed: unsupported URL
> ```

Hi! This branch was a crude attempt, given that I didn't have (and still don't have) access to a GitHub Enterprise server to test against.
The only piece of advice I can give you is to check the enterprise server URL, it should be a valid Swift URL ( eg. `https://my-ghes-server.com`) and not only the host.

Given that the community didn't show interested in this feature and that the main branch has made progress I'm not inclined to try to rebase and fix all merge conflicts. I will wait a bit for feedback but unless a lot of people chime in and provide support for this I will close PR

2024-07-16 11:18 UTC, FloThinksPi commented
> > Hm i tried out the pr branch and at first it seemed to work well however when starting against a github enterprise server i got following error which i could not trace town yet:
> > ```
> > Request to my-ghes-server.com/app/installations failed: unsupported URL
> > ```
> 
> Hi! This branch was a crude attempt, given that I didn't have (and still don't have) access to a GitHub Enterprise server to test against. The only piece of advice I can give you is to check the enterprise server URL, it should be a valid Swift URL ( eg. `https://my-ghes-server.com`) and not only the host.
> 
> Given that the community didn't show interested in this feature and that the main branch has made progress I'm not inclined to try to rebase and fix all merge conflicts. I will wait a bit for feedback but unless a lot of people chime in and provide support for this I will close PR

Thanks for the hint indeed it seemed i was missing the protocol and in addition the api path so usually:
`https://my-ghes-server.com/api/v3`. However i hit other issues maybe due to the age of the version the PR is build on.
Since there was a lot of change rebasing is not that straigt forward. I will try out cilicon for now as they have an option to pass a different github api url too.

2024-07-23 14:17 UTC, closed without merging